import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "@radix-ui/themes/styles.css";
import { Avatar, Box, Button, Card, Flex, Text, Theme } from "@radix-ui/themes";
import {
  Cross2Icon,
  GroupIcon,
  HomeIcon,
  InfoCircledIcon,
  Link1Icon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  PersonIcon,
  ReaderIcon,
  TrashIcon,
} from "@radix-ui/react-icons";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Revolt Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " p-8"}>
        <Theme>
          <Flex>
            <div className="relative">
              <Flex
                gap="2"
                direction="column"
                className="fixed left-0 top-0 w-[280px] h-[100vh] p-4 overflow-y-auto"
              >
                <img
                  src="https://app.revolt.chat/assets/wide.svg"
                  className="invert h-8 m-4"
                />

                <Card>
                  <Flex gap="3" align="center">
                    <Avatar
                      size="3"
                      src="https://s.gravatar.com/avatar/9e06b7b88685681c231eb47693300a18?size=40&default=https%3A%2F%2Fadmin.revolt.chat%2Fhonse.png"
                      radius="full"
                      fallback="T"
                    />
                    <Box>
                      <Text as="div" size="2" weight="bold">
                        insert@revolt.chat
                      </Text>
                      <Text as="div" size="2" color="gray">
                        Admin
                      </Text>
                    </Box>
                  </Flex>
                </Card>

                <Link href="/">
                  <Button variant="solid" className="!justify-start w-full">
                    <HomeIcon /> Home
                  </Button>
                </Link>
                <Button variant="surface" className="!justify-start">
                  <PersonIcon />
                  Team Members
                </Button>
                <Button variant="surface" className="!justify-start">
                  <GroupIcon />
                  Permissions & Groups
                </Button>
                <Button variant="surface" className="!justify-start">
                  <Link1Icon />
                  Integration Settings
                </Button>
                <Link href="/reports">
                  <Button variant="surface" className="!justify-start w-full">
                    <ReaderIcon /> Reports & Cases
                  </Button>
                </Link>
                <Button variant="surface" className="!justify-start">
                  <MagnifyingGlassIcon />
                  Search by ID
                </Button>
                <Button variant="surface" className="!justify-start">
                  <LockClosedIcon />
                  Authifier
                </Button>
                <Button variant="surface" className="!justify-start">
                  <TrashIcon />
                  Nuked Content
                </Button>
                <Button variant="surface" className="!justify-start">
                  <InfoCircledIcon />
                  About
                </Button>

                {/* <div className="w-[100%] border-t-[1px] border-t-gray" /> */}

                {/* {[
                  "Case: Server(s) ijghhjifg",
                  "Server: Balls!",
                  "User: userisreal",
                ].map((x, i) => (
                  <Flex
                    gap="2"
                    key={i}
                    className="overflow-hidden min-w-0 flex-shrink-0 hover-btn"
                  >
                    <Button
                      variant="outline"
                      className="whitespace-nowrap text-ellipsis overflow-hidden !block !flex-shrink flex-grow"
                    >
                      {x}
                    </Button>
                    <Button variant="outline" color="tomato" className="btn">
                      <Cross2Icon />
                    </Button>
                  </Flex>
                ))} */}
              </Flex>
            </div>
            <div className="w-[260px] flex-shrink-0" />
            {children}
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
